In [1]:
import pandas as pd

In [3]:
df_train = pd.read_csv('train.csv', low_memory=False)
df_test = pd.read_csv('test.csv', low_memory=False)

In [5]:
df_train.head()

,snapshot_dt,agreement,customer,target,a76154d74182dbdbe69cc30b71b94709,713bc35ae4a64ec4790712ab3ff2e7b0,142642bce57cac3a54f26d9c4a4ea164,64879933ebbcd196512dd71dede1b7fc,41b8f61fa021d3421510284f8e8ed8e6,d70cf72daf09e847b9d98f5cd110e874,...,b62f1cae6504d09ae4456042bc924802,cbdcd5b4417b44615f4205f532c09bf8,de41cfed08599c3ed288a56edcc5c768,7218c484a45b5cf830285bff9b436a9e,9a97b46bc29290671213a1d7f21016b9,8ce7e1924c8891f9ca267c926a71d4ad,7e9b2e50b011024e81f5c646fb436e28,bb496ecdfaf5fc8772d00ae34048ec29,5a105e8b9d40e1329780d62ea2265d8a,ad0234829205b9033196ba818f7a872b
0,1551398400,206429777,99860345,0,inf,"1,377262826",0,018,"21,38703704",-1,...,019,0,-1,0,-1,1.0,-1,NaN,2,0
1,1548979200,356198936,143066693,0,"2,857142857","0,718872084","26,66666667",017,"6,959459459",-1,...,01C,0,-1,0,-1,1.0,-1,NaN,1,1
2,1548979200,181800968,97211246,0,-1,-1,0,017,39,"0,1",...,01C,0,-inf,0,-1,0.0,0,NaN,0,2
3,1538352000,126060285,26277371,0,NaN,-1,NaN,01A,NaN,-1,...,018,NaN,-1,NaN,NaN,NaN,-1,NaN,3,1
4,1541030400,226351733,122502600,0,-1,-1,145,017,0,-1,...,01C,0,-1,0,-1,1.0,-1,NaN,2,1

In [84]:
df_train

,snapshot_dt,agreement,customer,target,a76154d74182dbdbe69cc30b71b94709,713bc35ae4a64ec4790712ab3ff2e7b0,142642bce57cac3a54f26d9c4a4ea164,64879933ebbcd196512dd71dede1b7fc,41b8f61fa021d3421510284f8e8ed8e6,d70cf72daf09e847b9d98f5cd110e874,...,cbdcd5b4417b44615f4205f532c09bf8,de41cfed08599c3ed288a56edcc5c768,7218c484a45b5cf830285bff9b436a9e,9a97b46bc29290671213a1d7f21016b9,8ce7e1924c8891f9ca267c926a71d4ad,7e9b2e50b011024e81f5c646fb436e28,bb496ecdfaf5fc8772d00ae34048ec29,5a105e8b9d40e1329780d62ea2265d8a,ad0234829205b9033196ba818f7a872b,is_train
0,1551398400,206429777,99860345,0,inf,"1,377262826",0,018,"21,38703704",-1,...,0,-1,0,-1,1.0,-1,NaN,2,0,1
1,1548979200,356198936,143066693,0,"2,857142857","0,718872084","26,66666667",017,"6,959459459",-1,...,0,-1,0,-1,1.0,-1,NaN,1,1,1
2,1548979200,181800968,97211246,0,-1,-1,0,017,39,"0,1",...,0,-inf,0,-1,0.0,0,NaN,0,2,1
3,1538352000,126060285,26277371,0,NaN,-1,NaN,01A,NaN,-1,...,NaN,-1,NaN,NaN,NaN,-1,NaN,3,1,1
4,1541030400,226351733,122502600,0,-1,-1,145,017,0,-1,...,0,-1,0,-1,1.0,-1,NaN,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90324,1551398400,110273415,28423322,1,-1,0,0,018,0,-1,...,0,-1,0,-1,0.0,-1,NaN,2,1,1
90325,1527811200,112664931,77404434,0,NaN,-1,NaN,017,NaN,-1,...,NaN,-1,NaN,NaN,NaN,0,NaN,3,2,1
90326,1535760000,76980636,47200630,0,"1,5","1,7991",0,017,0,-1,...,0,-1,0,-1,0.0,-1,NaN,0,0,1
90327,1546300800,73816241,43131184,0,NaN,-1,NaN,018,NaN,-1,...,NaN,-1,NaN,NaN,NaN,0,NaN,1,2,1
90328,1530403200,123926193,80418297,0,NaN,-1,NaN,017,NaN,-1,...,NaN,0,NaN,NaN,NaN,0,NaN,1,2,1

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90329 entries, 0 to 90328
Data columns (total 66 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   snapshot_dt                       90329 non-null  int64
 1   agreement                         90329 non-null  int64
 2   customer                          90329 non-null  int64
 3   target                            90329 non-null  int64
 4   a76154d74182dbdbe69cc30b71b94709  63579 non-null  object
 5   713bc35ae4a64ec4790712ab3ff2e7b0  90155 non-null  object
 6   142642bce57cac3a54f26d9c4a4ea164  63579 non-null  object
 7   64879933ebbcd196512dd71dede1b7fc  90185 non-null  object
 8   41b8f61fa021d3421510284f8e8ed8e6  63579 non-null  object
 9   d70cf72daf09e847b9d98f5cd110e874  90155 non-null  object
 10  47b359b06b472245ebf392f89c1984d9  13920 non-null  float64
 11  a4fc43c630d53f6b4fc24dcea3cdfdd6  1465 non-null   object
 12  20954702b0ca458c1b9cc94a2149dfae  63579 non-null  object
 13  d1e92bd0813153b4426efe76c284962a  13920 non-null  float64
 14  96ac93b9d41855f8f4154d101b7eec8f  1465 non-null   float64
 15  60678ed309bcdf3a7f66c3c0eaaa1008  1465 non-null   float64
 16  dc22bcce783424523515ca0e767f956d  90155 non-null  object
 17  de21a72f92151bd934313db21484d8db  90329 non-null  object
 18  6e3c7ee1446922e9affc2dec6d8515f5  63579 non-null  object
 19  3ab7560edc855076c9f82a1d067260ac  1635 non-null   float64
 20  c4e258b20763ff2f5eb3a9c0051b79f9  63579 non-null  object
 21  713c06ee08e923ef1deb2b49e6412d08  1635 non-null   float64
 22  56c259bfa606793bcebaab86f6b85433  90329 non-null  int64
 23  738c9267ed0535b048c9b4e6ecff0fb4  13920 non-null  float64
 24  1674cc7109143930d7062cf2bd15bc7a  90329 non-null  int64
 25  b55cf545a7986b074431f2d871729ce9  90155 non-null  object
 26  e5b53d22fc96aa7d26dc24ae635738e3  90155 non-null  object
 27  1d211cea131c727b11e844a32fecdf60  90155 non-null  object
 28  e2797b202accd48208bb55c5f42b3bd3  63579 non-null  object
 29  40420d27d2213916d22d5667fa9cc79d  90155 non-null  object
 30  56b9387690aec4bea7c0ead0cd2e24f7  90323 non-null  float64
 31  0866c8069f8eb9325d7aff3bc11aa4c6  90155 non-null  object
 32  d34fdde10bbb782474b10a70e8afe0f1  90155 non-null  object
 33  74035d01c87ff94f92a02d8b4c96db89  13920 non-null  object
 34  9592aaf089727a294080f269ded5b792  63579 non-null  object
 35  8ba3cf3fe186dd2da23b957bb173138a  90155 non-null  object
 36  0ca8d1267d125b2168c4d63e02f5af1e  13920 non-null  float64
 37  3c267b3313e203bfca261907cbeda7f9  1465 non-null   float64
 38  fc0ded9709cc8e822e4e3d5fd6e0eec2  1465 non-null   float64
 39  6b5813ceabe68652ddab5a4aa9b721e0  90155 non-null  object
 40  c82fc9c0e6b2751df53d7dd5c468de67  63579 non-null  object
 41  cb943d8843fff2f8467e9302993102de  63579 non-null  object
 42  c6f4e2f63b588bd5687ea6355b58b715  63579 non-null  object
 43  a7e2d20b01d09c3dc6c3e7597ba74ab3  63579 non-null  object
 44  234f65a21bdae522ae9e58d00af11dcf  90155 non-null  object
 45  519053282a77e76f836c4e2de8b729e1  90155 non-null  object
 46  f9608069a551280acfd81ef612ffaaa3  90155 non-null  object
 47  51cb8124c134e01bff98d8e796f87f5a  90155 non-null  object
 48  8e78b08a9f5993a6c3ac4bceef7a8dd8  63579 non-null  object
 49  5d16d06d10a707e2fcdec6f8fc8c4430  90155 non-null  object
 50  d459ebf68fc2817262bbdf585ee417fa  90155 non-null  object
 51  754dee610d3bc5ef654ef2b9c4328c2d  13920 non-null  object
 52  3bd82d077c83e58e0682d35477517cf0  63579 non-null  object
 53  e4c6835684496e9fa5c8292c8bcaa4b3  90155 non-null  object
 54  b595cbe5ed2d1a3b983c039ae8ff405f  90155 non-null  float64
 55  26ead531bb1ccaad478f1989fc1c8d9b  63579 non-null  object
 56  b62f1cae6504d09ae4456042bc924802  90189 non-null  object
 57  cbdcd5b4417b44615f4205f532c09bf8  63579 non-null  object
 58  de41cfed08599c3ed288a56edcc5c768  90155 non-null  object
 59  7218c484a45b5cf830285bff9b436a9e  63579 non-null  object
 60  9a97b46bc29290671213a1d7f21016b9  63579 non-null  object
 61  8ce7e1924c8891f9ca267c926a71d4ad  63579 non-null  float64
 62  7e9b2e50b011024e81f5c646fb436e28  90155 non-null  object
 63  bb496ecdfaf5fc8772d00ae34048ec29  13920 non-null  float64
 64  5a105e8b9d40e1329780d62ea2265d8a  90329 non-null  int64
 65  ad0234829205b9033196ba818f7a872b  90329 non-null  int64
dtypes: float64(14), int64(8), object(44)
memory usage: 45.5+ MB

Gemini

In [59]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import LabelEncoder

# Assume df_train and df_test are already loaded in your environment

# 1. Concatenate for consistent preprocessing
# We tag them to separate them later
df_train['is_train'] = 1
df_test['is_train'] = 0
df_test['target'] = np.nan # Placeholder

# Combine
full_data = pd.concat([df_train, df_test], axis=0).reset_index(drop=True)

# 2. Define ID columns to drop from features
# snapshot_dt might contain trend info, but usually, we drop it for basic classification
id_cols = ['agreement', 'customer', 'snapshot_dt', 'is_train', 'target']
features = [c for c in full_data.columns if c not in id_cols]

# 3. Handle Categorical Features (Object columns)
# We use Label Encoding: turning strings into integers. 
# XGBoost handles integers well even if they represent categories.
object_cols = full_data.select_dtypes(include=['object']).columns

print(f"Encoding {len(object_cols)} categorical columns...")

for col in object_cols:
    le = LabelEncoder()
    # Convert to string to handle mixed types/NaNs uniformly for the encoder
    full_data[col] = full_data[col].astype(str)
    full_data[col] = le.fit_transform(full_data[col])

# 4. Split back into Train and Test
X = full_data[full_data['is_train'] == 1][features]
y = full_data[full_data['is_train'] == 1]['target']
X_test = full_data[full_data['is_train'] == 0][features]

# 5. Model Training with Cross-Validation
# We use K-Fold to ensure the model is stable and not overfitting
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
oof_preds = np.zeros(len(X))
test_preds = np.zeros(len(X_test))

print("Starting Training...")

for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
    X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]
    
    # XGBoost configuration
    model = xgb.XGBClassifier(
        n_estimators=1000,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        n_jobs=-1,
        random_state=42,
        eval_metric='auc',
        early_stopping_rounds=50,
        # 'enable_categorical': True # Uncomment if using very recent XGBoost versions
    )
    
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=False
    )
    
    # Predict validation set (to check accuracy)
    val_pred = model.predict_proba(X_val)[:, 1]
    oof_preds[val_idx] = val_pred
    
    # Predict on actual test set
    test_preds += model.predict_proba(X_test)[:, 1] / kf.get_n_splits()
    
    score = roc_auc_score(y_val, val_pred)
    print(f"Fold {fold+1} AUC: {score:.4f}")

# 6. Final Evaluation
overall_auc = roc_auc_score(y, oof_preds)
print(f"--- Overall CV AUC: {overall_auc:.4f} ---")



# 7. Create Submission DataFrame
submission = pd.DataFrame({
    'customer': df_test['customer'], # Assuming customer ID is required for submission
    'target': test_preds
})

# submission.to_csv('submission.csv', index=False)
print("Prediction complete. Head of submission:")
print(submission.head())

Encoding 44 categorical columns...
Starting Training...
Fold 1 AUC: 0.7155
Fold 2 AUC: 0.7004
Fold 3 AUC: 0.7298
Fold 4 AUC: 0.7186
Fold 5 AUC: 0.7053
--- Overall CV AUC: 0.7071 ---
Prediction complete. Head of submission:
    customer    target
0  119156836  0.015041
1   46948414  0.017527
2   85702891  0.009671
3   84487348  0.017923
4  122306861  0.015570

In [60]:
# Вариант B: подбор порога по OOF (максимизируем F1)
from sklearn.metrics import precision_recall_curve, f1_score, accuracy_score

precision, recall, thresholds = precision_recall_curve(y, oof_preds)
# precision_recall_curve возвращает thresholds длиной len(precision)-1
f1_scores = 2 * precision[:-1] * recall[:-1] / (precision[:-1] + recall[:-1] + 1e-12)
best_idx = f1_scores.argmax()
best_thr = thresholds[best_idx]

print(f"Лучший порог (по F1 на OOF): {best_thr:.4f}")
print(f"Лучший F1 на OOF: {f1_scores[best_idx]:.4f}")

test_pred_binary = (test_preds >= best_thr).astype(int)
oof_pred_binary = (oof_preds >= best_thr).astype(int)

print(f"F1 (best_thr) on OOF: {f1_score(y, oof_pred_binary):.4f}")
print(f"Accuracy (best_thr) on OOF: {accuracy_score(y, oof_pred_binary):.4f}")

Лучший порог (по F1 на OOF): 0.0642
Лучший F1 на OOF: 0.1397
F1 (best_thr) on OOF: 0.1397
Accuracy (best_thr) on OOF: 0.9542

In [61]:
submission['target'] = (submission['target'] >= 0.0642).astype(int)

In [62]:
submission

        customer  target
0      119156836       0
1       46948414       0
2       85702891       0
3       84487348       0
4      122306861       0
...          ...     ...
10032   83253522       0
10033   39917601       0
10034   23787469       0
10035  146734036       0
10036   47005063       0

[10037 rows x 2 columns]

In [63]:
submission.to_csv('answer.csv')

Optuna

In [92]:
df_train[object_cols]

,64879933ebbcd196512dd71dede1b7fc,d1e92bd0813153b4426efe76c284962a,60678ed309bcdf3a7f66c3c0eaaa1008,713c06ee08e923ef1deb2b49e6412d08,738c9267ed0535b048c9b4e6ecff0fb4,56b9387690aec4bea7c0ead0cd2e24f7,fc0ded9709cc8e822e4e3d5fd6e0eec2,b62f1cae6504d09ae4456042bc924802,bb496ecdfaf5fc8772d00ae34048ec29
0,018,NaN,NaN,NaN,NaN,17.0,NaN,019,NaN
1,017,NaN,NaN,NaN,NaN,16.0,NaN,01C,NaN
2,017,NaN,NaN,NaN,NaN,17.0,NaN,01C,NaN
3,01A,NaN,NaN,NaN,NaN,17.0,NaN,018,NaN
4,017,NaN,NaN,NaN,NaN,16.0,NaN,01C,NaN
...,...,...,...,...,...,...,...,...,...
90324,018,NaN,NaN,NaN,NaN,16.0,NaN,018,NaN
90325,017,NaN,NaN,NaN,NaN,17.0,NaN,018,NaN
90326,017,NaN,NaN,NaN,NaN,17.0,NaN,01C,NaN
90327,018,NaN,NaN,NaN,NaN,17.0,NaN,017,NaN
90328,017,NaN,NaN,NaN,NaN,16.0,NaN,01C,NaN

In [91]:
object_cols = ['64879933ebbcd196512dd71dede1b7fc', 'd1e92bd0813153b4426efe76c284962a', \
            '60678ed309bcdf3a7f66c3c0eaaa1008', '713c06ee08e923ef1deb2b49e6412d08', \
            '738c9267ed0535b048c9b4e6ecff0fb4', '56b9387690aec4bea7c0ead0cd2e24f7', \
            'fc0ded9709cc8e822e4e3d5fd6e0eec2', \
            'b62f1cae6504d09ae4456042bc924802', 'bb496ecdfaf5fc8772d00ae34048ec29']

In [ ]:
id_cols = ['agreement', 'customer', 'snapshot_dt', 'is_train', 'target']
to_drop = ['0ca8d1267d125b2168c4d63e02f5af1e', '74035d01c87ff94f92a02d8b4c96db89']
object_cols = ['64879933ebbcd196512dd71dede1b7fc', 'd1e92bd0813153b4426efe76c284962a', \
            '60678ed309bcdf3a7f66c3c0eaaa1008', '713c06ee08e923ef1deb2b49e6412d08', \
            '738c9267ed0535b048c9b4e6ecff0fb4', '56b9387690aec4bea7c0ead0cd2e24f7', \
            'fc0ded9709cc8e822e4e3d5fd6e0eec2', \
            'b62f1cae6504d09ae4456042bc924802', 'bb496ecdfaf5fc8772d00ae34048ec29']
features = [c for c in full_data.columns if c not in id_cols and c not in to_drop]
numeric_features = [c for c in features if c not in object_cols]

# 3. Handle Categorical Features (Object columns)
# We use Label Encoding: turning strings into integers.
# XGBoost handles integers well even if they represent categories.

print(f"Encoding {len(object_cols)} categorical columns...")

for col in object_cols:
    le = LabelEncoder()
    # Convert to string to handle mixed types/NaNs uniformly for the encoder
    full_data[col] = full_data[col].astype(str)
    full_data[col] = le.fit_transform(full_data[col])

for col in numeric_features:
    if full_data[col].dtype == 'object':
        full_data[col] = full_data[col].str.replace(',', '.', regex=False)
    full_data[col] = full_data[col].astype(float)

full_data = full_data.replace(['inf', np.inf, -np.inf], np.nan)

# 4. Split back into Train and Test
X = full_data[full_data['is_train'] == 1][features]
y = full_data[full_data['is_train'] == 1]['target']
X_test = full_data[full_data['is_train'] == 0][features]

In [75]:
# --- Optuna + xgb.train (совместимо с версиями XGBoost, где sklearn.fit не принимает callbacks) ---
import optuna
from optuna.integration import XGBoostPruningCallback
from optuna.samplers import TPESampler
from optuna.pruners import MedianPruner
import xgboost as xgb
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
import numpy as np
import pandas as pd

# Функция-цель для Optuna
def objective(trial):
    # пространство поиска
    params = {
        'objective': 'binary:logistic',
        'eval_metric': 'auc',
        'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
        'max_depth': int(trial.suggest_int('max_depth', 3, 10)),
        'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
        'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
        'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
        'min_child_weight': int(trial.suggest_int('min_child_weight', 1, 20)),
        'verbosity': 0,
        'seed': 42,
        # 'tree_method': 'hist',   # можете раскомментировать при больших датасетах или GPU 'gpu_hist'
    }

    kf_inner = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = []

    for tr_idx, val_idx in kf_inner.split(X, y):
        X_tr, X_val = X.iloc[tr_idx], X.iloc[val_idx]
        y_tr, y_val = y.iloc[tr_idx], y.iloc[val_idx]

        dtrain = xgb.DMatrix(X_tr, label=y_tr)
        dval = xgb.DMatrix(X_val, label=y_val)

        evals = [(dval, 'valid')]

        # Добавляем pruning callback — если Optuna поддерживает для вашей версии XGBoost
        pruning_cb = XGBoostPruningCallback(trial, "valid-auc")

        # Тренируем через xgb.train — поддерживает early_stopping_rounds
        bst = xgb.train(
            params,
            dtrain,
            num_boost_round=2000,
            evals=evals,
            early_stopping_rounds=100,
            verbose_eval=False,
            callbacks=[pruning_cb] if pruning_cb is not None else None
        )

        # Предсказания на валидации: используем оптимальное количество деревьев, если есть
        if hasattr(bst, 'best_ntree_limit'):
            val_pred = bst.predict(dval, ntree_limit=bst.best_ntree_limit)
        else:
            val_pred = bst.predict(dval)

        scores.append(roc_auc_score(y_val, val_pred))

    return float(np.mean(scores))


# Создаём study
sampler = TPESampler(seed=42)
pruner = MedianPruner(n_startup_trials=5, n_warmup_steps=10)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=pruner)

N_TRIALS = 50  # подберите под ресурсы
print("Запуск Optuna-оптимизации...")
study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=True)

print("Лучший trial:")
print(f"  CV AUC = {study.best_value:.5f}")
print("  Params:")
for k, v in study.best_params.items():
    print(f"    {k}: {v}")

# --- Финальное обучение (5-fold CV), используя xgb.train для каждого фолда ---
best = study.best_params
final_params = {
    'objective': 'binary:logistic',
    'eval_metric': 'auc',
    'learning_rate': best['learning_rate'],
    'max_depth': int(best['max_depth']),
    'subsample': best['subsample'],
    'colsample_bytree': best['colsample_bytree'],
    'alpha': best['reg_alpha'],
    'lambda': best['reg_lambda'],
    'min_child_weight': int(best['min_child_weight']),
    'verbosity': 0,
    'seed': 42,
}

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
oof_preds = np.zeros(len(X))
test_preds = np.zeros(len(X_test))

dtest = xgb.DMatrix(X_test)

print("Тренируем финальные модели и собираем OOF + предсказания на тесте...")
for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

    dtrain = xgb.DMatrix(X_tr, label=y_tr)
    dval = xgb.DMatrix(X_val, label=y_val)

    bst = xgb.train(
        final_params,
        dtrain,
        num_boost_round=2000,
        evals=[(dval, 'valid')],
        early_stopping_rounds=100,
        verbose_eval=False
    )

    # val predictions
    if hasattr(bst, 'best_ntree_limit'):
        val_pred = bst.predict(dval, ntree_limit=bst.best_ntree_limit)
        test_pred = bst.predict(dtest, ntree_limit=bst.best_ntree_limit)
    else:
        val_pred = bst.predict(dval)
        test_pred = bst.predict(dtest)

    oof_preds[val_idx] = val_pred
    test_preds += test_pred / kf.get_n_splits()

    fold_score = roc_auc_score(y_val, val_pred)
    print(f"Fold {fold+1} AUC: {fold_score:.4f}")

overall_auc = roc_auc_score(y, oof_preds)
print(f"--- Overall CV AUC (final): {overall_auc:.4f} ---")

submission = pd.DataFrame({
    'customer': df_test['customer'],
    'target': test_preds
})
print("Head of submission:")
print(submission.head())
# --- Конец блока ---

[I 2025-11-28 15:27:03,845] A new study created in memory with name: no-name-3147cafa-67c3-4d99-94a3-f37ba276bc82

Запуск Optuna-оптимизации...

  0%|          | 0/50 [00:00<?, ?it/s]

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(

[I 2025-11-28 15:27:12,203] Trial 0 finished with value: 0.6925619874512929 and parameters: {'learning_rate': 0.03574712922600244, 'max_depth': 10, 'subsample': 0.8659969709057025, 'colsample_bytree': 0.759195090518222, 'reg_alpha': 2.5361081166471375e-07, 'reg_lambda': 2.5348407664333426e-07, 'min_child_weight': 2}. Best is trial 0 with value: 0.6925619874512929.

/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 92 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 93 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 94 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 95 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 96 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 97 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 98 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 99 is already reported.
  warnings.warn(

[I 2025-11-28 15:27:18,030] Trial 1 finished with value: 0.6852552930256735 and parameters: {'learning_rate': 0.19030368381735815, 'max_depth': 7, 'subsample': 0.8540362888980227, 'colsample_bytree': 0.41235069657748147, 'reg_alpha': 5.360294728728285, 'reg_lambda': 0.31044435499483225, 'min_child_weight': 5}. Best is trial 0 with value: 0.6925619874512929.

/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 92 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 93 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 94 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 95 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 96 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 97 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 98 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 99 is already reported.
  warnings.warn(

[I 2025-11-28 15:27:28,053] Trial 2 finished with value: 0.7170802619351915 and parameters: {'learning_rate': 0.01855998084649059, 'max_depth': 4, 'subsample': 0.6521211214797689, 'colsample_bytree': 0.7148538589793427, 'reg_alpha': 7.71800699380605e-05, 'reg_lambda': 4.17890272377219e-06, 'min_child_weight': 13}. Best is trial 2 with value: 0.7170802619351915.

/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 92 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 93 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 94 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 95 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 96 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 97 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 98 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 99 is already reported.
  warnings.warn(

[I 2025-11-28 15:27:39,514] Trial 3 finished with value: 0.7153409498263068 and parameters: {'learning_rate': 0.01607123851203988, 'max_depth': 5, 'subsample': 0.6831809216468459, 'colsample_bytree': 0.6736419905302216, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07, 'min_child_weight': 11}. Best is trial 2 with value: 0.7170802619351915.

/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 92 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 93 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 94 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 95 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 96 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 97 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 98 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 99 is already reported.
  warnings.warn(

[I 2025-11-28 15:27:47,170] Trial 4 finished with value: 0.7135804732556482 and parameters: {'learning_rate': 0.07500118950416987, 'max_depth': 3, 'subsample': 0.8037724259507192, 'colsample_bytree': 0.502314474212375, 'reg_alpha': 3.850031979199519e-08, 'reg_lambda': 3.4671276804481113, 'min_child_weight': 20}. Best is trial 2 with value: 0.7170802619351915.

/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 92 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 93 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 94 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 95 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 96 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 97 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 98 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 99 is already reported.
  warnings.warn(

[I 2025-11-28 15:27:53,032] Trial 5 finished with value: 0.6808309388472764 and parameters: {'learning_rate': 0.1563510870813346, 'max_depth': 5, 'subsample': 0.5488360570031919, 'colsample_bytree': 0.8105398159072941, 'reg_alpha': 9.148975058772307e-05, 'reg_lambda': 1.254134495897175e-07, 'min_child_weight': 10}. Best is trial 2 with value: 0.7170802619351915.

/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 92 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 93 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 94 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 95 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 96 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 97 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 98 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 99 is already reported.
  warnings.warn(

[I 2025-11-28 15:28:09,111] Trial 6 pruned. Trial was pruned at iteration 369.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(

[I 2025-11-28 15:28:18,945] Trial 7 pruned. Trial was pruned at iteration 145.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:28:19,234] Trial 8 pruned. Trial was pruned at iteration 10.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(

[I 2025-11-28 15:28:35,068] Trial 9 finished with value: 0.7140878907277735 and parameters: {'learning_rate': 0.03364867144187954, 'max_depth': 5, 'subsample': 0.7713480415791243, 'colsample_bytree': 0.4845545349848576, 'reg_alpha': 0.16587190283399655, 'reg_lambda': 4.6876566400928895e-08, 'min_child_weight': 20}. Best is trial 2 with value: 0.7170802619351915.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(

[I 2025-11-28 15:28:41,062] Trial 10 pruned. Trial was pruned at iteration 120.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:28:42,626] Trial 11 pruned. Trial was pruned at iteration 121.
[I 2025-11-28 15:28:42,824] Trial 12 pruned. Trial was pruned at iteration 10.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(

[I 2025-11-28 15:28:45,738] Trial 13 pruned. Trial was pruned at iteration 257.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:28:46,032] Trial 14 pruned. Trial was pruned at iteration 12.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:28:46,260] Trial 15 pruned. Trial was pruned at iteration 10.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:28:46,493] Trial 16 pruned. Trial was pruned at iteration 12.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:28:47,705] Trial 17 pruned. Trial was pruned at iteration 145.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:28:48,042] Trial 18 pruned. Trial was pruned at iteration 12.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:28:48,313] Trial 19 pruned. Trial was pruned at iteration 20.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:28:49,078] Trial 20 pruned. Trial was pruned at iteration 92.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:28:49,949] Trial 21 pruned. Trial was pruned at iteration 127.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:28:50,808] Trial 22 pruned. Trial was pruned at iteration 143.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(

[I 2025-11-28 15:28:54,095] Trial 23 pruned. Trial was pruned at iteration 257.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(

[I 2025-11-28 15:28:57,644] Trial 24 pruned. Trial was pruned at iteration 257.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:28:57,868] Trial 25 pruned. Trial was pruned at iteration 12.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:28:58,104] Trial 26 pruned. Trial was pruned at iteration 12.
[I 2025-11-28 15:28:58,292] Trial 27 pruned. Trial was pruned at iteration 10.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(

[I 2025-11-28 15:29:04,144] Trial 28 finished with value: 0.7032995301486934 and parameters: {'learning_rate': 0.060188639991540574, 'max_depth': 7, 'subsample': 0.7376537256437458, 'colsample_bytree': 0.8324519852344542, 'reg_alpha': 0.00022085594529978628, 'reg_lambda': 1.0716284377172181e-06, 'min_child_weight': 12}. Best is trial 2 with value: 0.7170802619351915.

/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 92 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 93 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 94 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 95 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 96 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 97 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 98 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 99 is already reported.
  warnings.warn(

[I 2025-11-28 15:29:14,388] Trial 29 finished with value: 0.7130003407674447 and parameters: {'learning_rate': 0.03720296265656419, 'max_depth': 5, 'subsample': 0.7722487302259855, 'colsample_bytree': 0.5378880789675828, 'reg_alpha': 1.2905900902759882e-07, 'reg_lambda': 2.391829997442218e-07, 'min_child_weight': 8}. Best is trial 2 with value: 0.7170802619351915.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:29:14,667] Trial 30 pruned. Trial was pruned at iteration 10.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:29:14,907] Trial 31 pruned. Trial was pruned at iteration 10.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:29:15,175] Trial 32 pruned. Trial was pruned at iteration 10.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(

[I 2025-11-28 15:29:22,037] Trial 33 finished with value: 0.7145080056817046 and parameters: {'learning_rate': 0.06712252867295458, 'max_depth': 4, 'subsample': 0.6815612813384654, 'colsample_bytree': 0.4452010642054477, 'reg_alpha': 2.594708779465359e-08, 'reg_lambda': 3.231252297984914, 'min_child_weight': 20}. Best is trial 2 with value: 0.7170802619351915.

/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:29:22,276] Trial 34 pruned. Trial was pruned at iteration 10.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(

[I 2025-11-28 15:29:30,183] Trial 35 finished with value: 0.7110034607852509 and parameters: {'learning_rate': 0.047361710938756456, 'max_depth': 5, 'subsample': 0.6786084638674917, 'colsample_bytree': 0.5121397340659359, 'reg_alpha': 0.16200625516497127, 'reg_lambda': 2.962023665670169e-07, 'min_child_weight': 19}. Best is trial 2 with value: 0.7170802619351915.

/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 92 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 93 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 94 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 95 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 96 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 97 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 98 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 99 is already reported.
  warnings.warn(

[I 2025-11-28 15:29:38,341] Trial 36 finished with value: 0.714375227312263 and parameters: {'learning_rate': 0.032309701549783604, 'max_depth': 6, 'subsample': 0.6188289507957463, 'colsample_bytree': 0.42917857523298825, 'reg_alpha': 1.1706873481485587e-08, 'reg_lambda': 0.6038044478073925, 'min_child_weight': 11}. Best is trial 2 with value: 0.7170802619351915.

/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 92 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 93 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 94 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 95 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 96 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 97 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 98 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 99 is already reported.
  warnings.warn(

[I 2025-11-28 15:29:42,206] Trial 37 pruned. Trial was pruned at iteration 265.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:29:44,168] Trial 38 pruned. Trial was pruned at iteration 177.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:29:44,437] Trial 39 pruned. Trial was pruned at iteration 10.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:29:44,704] Trial 40 pruned. Trial was pruned at iteration 10.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(

[I 2025-11-28 15:29:47,633] Trial 41 pruned. Trial was pruned at iteration 176.
[I 2025-11-28 15:29:48,987] Trial 42 pruned. Trial was pruned at iteration 177.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(

[I 2025-11-28 15:29:53,086] Trial 43 pruned. Trial was pruned at iteration 257.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:29:53,552] Trial 44 pruned. Trial was pruned at iteration 10.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 0 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 2 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 3 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 11 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 12 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 13 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 14 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 15 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 16 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 17 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 18 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 19 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 20 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 21 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 22 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 23 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 24 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 25 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 26 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 27 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 28 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 29 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 30 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 31 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 32 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 33 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 34 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 35 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 36 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 37 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 38 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 39 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 40 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 41 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 42 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 43 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 44 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 45 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 46 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 47 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 48 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 49 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 50 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 51 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 52 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 53 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 54 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 55 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 56 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 57 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 58 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 59 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 60 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 61 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 62 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 63 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 64 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 65 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 66 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 67 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 68 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 69 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 70 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 71 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 72 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 73 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 74 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 75 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 76 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 77 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 78 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 79 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 80 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 81 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 82 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 83 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 84 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 85 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 86 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 87 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 88 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 89 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 90 is already reported.
  warnings.warn(
/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 91 is already reported.
  warnings.warn(

[I 2025-11-28 15:30:27,185] Trial 45 finished with value: 0.7157253637212048 and parameters: {'learning_rate': 0.010126172924747998, 'max_depth': 5, 'subsample': 0.5787401789648273, 'colsample_bytree': 0.6780938637942896, 'reg_alpha': 0.00018710433571323334, 'reg_lambda': 1.2612256709615817e-05, 'min_child_weight': 13}. Best is trial 2 with value: 0.7170802619351915.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:30:27,405] Trial 46 pruned. Trial was pruned at iteration 10.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:30:27,736] Trial 47 pruned. Trial was pruned at iteration 10.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:30:28,318] Trial 48 pruned. Trial was pruned at iteration 38.

/tmp/ipykernel_52141/4253494091.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_52141/4253494091.py:20: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),
/tmp/ipykernel_52141/4253494091.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.4, 1.0),
/tmp/ipykernel_52141/4253494091.py:22: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),   # L1
/tmp/ipykernel_52141/4253494091.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0), # L2

[I 2025-11-28 15:30:30,071] Trial 49 pruned. Trial was pruned at iteration 172.
Лучший trial:
  CV AUC = 0.71708
  Params:
    learning_rate: 0.01855998084649059
    max_depth: 4
    subsample: 0.6521211214797689
    colsample_bytree: 0.7148538589793427
    reg_alpha: 7.71800699380605e-05
    reg_lambda: 4.17890272377219e-06
    min_child_weight: 13
Тренируем финальные модели и собираем OOF + предсказания на тесте...
Fold 1 AUC: 0.7218
Fold 2 AUC: 0.7012
Fold 3 AUC: 0.7315
Fold 4 AUC: 0.7237
Fold 5 AUC: 0.7072
--- Overall CV AUC (final): 0.7167 ---
Head of submission:
    customer    target
0  119156836  0.014680
1   46948414  0.021441
2   85702891  0.007159
3   84487348  0.016535
4  122306861  0.014927

Получение предсказаний

In [76]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

# ... (Assume you have run the XGBoost training code from the previous step)
# ... (You have 'y' (true labels) and 'oof_preds' (probabilities) ready)

# --- 1. Find the Perfect Threshold for BINARY AUC ---
# We simulate the submission format on our validation data to find the best cutoff.

thresholds = np.linspace(0.01, 0.99, 100)
best_threshold = 0.5
best_binary_auc = 0.0

print("Searching for optimal threshold to maximize Binary AUC...")

for thresh in thresholds:
    # Binarize the OOF predictions
    binary_preds = (oof_preds >= thresh).astype(int)
    
    # Calculate AUC on the BINARY output (as the system will do)
    score = roc_auc_score(y, binary_preds)
    
    if score > best_binary_auc:
        best_binary_auc = score
        best_threshold = thresh

print(f"\nBest Threshold found: {best_threshold:.4f}")
print(f"Max validation Binary AUC: {best_binary_auc:.4f}")

# Check if we meet the requirement
if best_binary_auc > 0.7:
    print("✅ Success! The model is expected to pass the 0.7 barrier.")
else:
    print("⚠️ Warning: The model might struggle to reach 0.7. Try feature engineering or different models.")

# --- 2. Create the Submission File ---

# Apply the best threshold to the Test Probabilities
test_binary_predictions = (test_preds >= best_threshold).astype(int)

# Create DataFrame
submission = pd.DataFrame({
    'customer': df_test['customer'],
    'target': test_binary_predictions
})

# Verify constraints
print("\nSubmission Check:")
print(f"Unique values in target: {submission['target'].unique()}") # Should be [0 1] or [1 0]
print(f"Data Type: {submission['target'].dtype}") # Should be int32 or int64

# --- 3. Save ---
submission.to_csv('answers.csv', index=False)
print("File 'answers.csv' saved successfully.")

Searching for optimal threshold to maximize Binary AUC...

Best Threshold found: 0.0199
Max validation Binary AUC: 0.6665
⚠️ Warning: The model might struggle to reach 0.7. Try feature engineering or different models.

Submission Check:
Unique values in target: [0 1]
Data Type: int64
File 'answers.csv' saved successfully.

CatBoost

In [78]:
# Ensure you have catboost installed: pip install catboost
from catboost import CatBoostClassifier, Pool

# 1. Prepare Data (Keep NaN as is, CatBoost handles them)
# Just do basic LabelEncoding for Object columns so they are strings or ints
# (CatBoost can handle strings, but ints are safer for memory)
X = df_train.drop(['target', 'snapshot_dt', 'agreement', 'is_train'], axis=1, errors='ignore')
y = df_train['target']
X_test_cb = df_test.drop(['target', 'snapshot_dt', 'agreement', 'is_train'], axis=1, errors='ignore')

# Identify categorical features indices
cat_features_indices = np.where(X.dtypes == object)[0]

# Fill NaNs in object columns with "MISSING" so CatBoost treats them as a category
X.iloc[:, cat_features_indices] = X.iloc[:, cat_features_indices].fillna("MISSING")
X_test_cb.iloc[:, cat_features_indices] = X_test_cb.iloc[:, cat_features_indices].fillna("MISSING")

# 2. Training with CatBoost
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
oof_preds = np.zeros(len(X))
test_preds = np.zeros(len(X_test_cb))

# Assuming X, y, X_test_cb, and cat_features_indices are set up from the previous step

# CatBoost only works with strings or integers for categorical features.
# We must convert all categorical features to string type.

print("Fixing categorical feature types...")

# 1. Get the list of categorical column names
cat_feature_names = X.columns[cat_features_indices]

# 2. Convert to string in both train and test sets
for col in cat_feature_names:
    # Use .astype(str) to safely convert all content, including -2.0 and NaN, to a unique string
    X[col] = X[col].astype(str).fillna("MISSING_STR")
    X_test_cb[col] = X_test_cb[col].astype(str).fillna("MISSING_STR")

print("Type conversion complete. Ready for CatBoost training.")

# Now proceed with the training loop:
# for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
#     ...
#     model.fit(...)

print("Starting CatBoost...")

for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]
    
    model = CatBoostClassifier(
        iterations=2000,
        learning_rate=0.05,
        depth=6,
        loss_function='Logloss',
        eval_metric='AUC',
        cat_features=cat_features_indices, # AUTOMATIC TARGET ENCODING HAPPENS HERE
        auto_class_weights='Balanced',     # AUTOMATICALLY FIXES IMBALANCE
        early_stopping_rounds=100,
        verbose=100,
        task_type="CPU" # or GPU
    )
    
    model.fit(
        X_tr, y_tr,
        eval_set=(X_val, y_val),
        use_best_model=True
    )
    
    oof_preds[val_idx] = model.predict_proba(X_val)[:, 1]
    test_preds += model.predict_proba(X_test_cb)[:, 1] / 5

# 3. Find Optimal Threshold (Same as before)
thresholds = np.linspace(0.01, 0.99, 100)
best_threshold = 0.5
best_score = 0.0

for t in thresholds:
    score = roc_auc_score(y, (oof_preds > t).astype(int))
    if score > best_score:
        best_score = score
        best_threshold = t

print(f"Best Binary AUC: {best_score}")
print(f"Best Threshold: {best_threshold}")

# 4. Generate Answer
submission = pd.DataFrame({
    'customer': df_test['customer'],
    'target': (test_preds > best_threshold).astype(int)
})
submission.to_csv('answers.csv', index=False)

/tmp/ipykernel_52141/294345757.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0        MISSING
1           -2.0
2        MISSING
3        MISSING
4        MISSING
          ...
10032    MISSING
10033    MISSING
10034    MISSING
10035    MISSING
10036    MISSING
Name: a4fc43c630d53f6b4fc24dcea3cdfdd6, Length: 10037, dtype: object' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  X_test_cb.iloc[:, cat_features_indices] = X_test_cb.iloc[:, cat_features_indices].fillna("MISSING")
/tmp/ipykernel_52141/294345757.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0        MISSING
1        MISSING
2        MISSING
3        MISSING
4        MISSING
          ...
10032    MISSING
10033    MISSING
10034    MISSING
10035    MISSING
10036    MISSING
Name: 754dee610d3bc5ef654ef2b9c4328c2d, Length: 10037, dtype: object' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  X_test_cb.iloc[:, cat_features_indices] = X_test_cb.iloc[:, cat_features_indices].fillna("MISSING")
/tmp/ipykernel_52141/294345757.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0            0.0
1        MISSING
2        MISSING
3        MISSING
4            0.0
          ...
10032    MISSING
10033        0.0
10034        0.0
10035        0.0
10036        0.0
Name: 7218c484a45b5cf830285bff9b436a9e, Length: 10037, dtype: object' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  X_test_cb.iloc[:, cat_features_indices] = X_test_cb.iloc[:, cat_features_indices].fillna("MISSING")

Fixing categorical feature types...
Type conversion complete. Ready for CatBoost training.
Starting CatBoost...
0:	test: 0.5935749	best: 0.5935749 (0)	total: 132ms	remaining: 4m 23s
100:	test: 0.6903799	best: 0.6904442 (97)	total: 25.2s	remaining: 7m 53s
200:	test: 0.6883617	best: 0.6916427 (139)	total: 52s	remaining: 7m 44s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6916426569
bestIteration = 139

Shrink model to first 140 iterations.
0:	test: 0.6196824	best: 0.6196824 (0)	total: 248ms	remaining: 8m 15s
100:	test: 0.6549033	best: 0.6569946 (69)	total: 27.4s	remaining: 8m 35s
200:	test: 0.6583217	best: 0.6595696 (191)	total: 51.6s	remaining: 7m 42s
300:	test: 0.6491847	best: 0.6604506 (215)	total: 1m 19s	remaining: 7m 28s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6604505512
bestIteration = 215

Shrink model to first 216 iterations.
0:	test: 0.5784202	best: 0.5784202 (0)	total: 154ms	remaining: 5m 7s
100:	test: 0.6752092	best: 0.6753989 (99)	total: 26.3s	remaining: 8m 14s
200:	test: 0.6738151	best: 0.6763477 (165)	total: 52.8s	remaining: 7m 52s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6763476837
bestIteration = 165

Shrink model to first 166 iterations.
0:	test: 0.6081944	best: 0.6081944 (0)	total: 354ms	remaining: 11m 48s
100:	test: 0.6639160	best: 0.6644872 (94)	total: 31.8s	remaining: 9m 57s
200:	test: 0.6700923	best: 0.6708040 (197)	total: 1m 2s	remaining: 9m 17s
300:	test: 0.6776405	best: 0.6793031 (286)	total: 1m 35s	remaining: 8m 58s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.679303129
bestIteration = 286

Shrink model to first 287 iterations.
0:	test: 0.6159635	best: 0.6159635 (0)	total: 229ms	remaining: 7m 38s
100:	test: 0.6585378	best: 0.6593587 (95)	total: 31s	remaining: 9m 42s
200:	test: 0.6538544	best: 0.6612649 (112)	total: 1m 3s	remaining: 9m 28s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.661264869
bestIteration = 112

Shrink model to first 113 iterations.
Best Binary AUC: 0.6313740216617914
Best Threshold: 0.5148484848484849

In [83]:
import optuna
from catboost import CatBoostClassifier, Pool
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
import numpy as np
import pandas as pd

# --- Подготовка данных (как у вас) ---
X = df_train.drop(['target', 'snapshot_dt', 'agreement', 'is_train'], axis=1, errors='ignore')
y = df_train['target']
X_test_cb = df_test.drop(['target', 'snapshot_dt', 'agreement', 'is_train'], axis=1, errors='ignore')

cat_features_indices = np.where(X.dtypes == object)[0]

X.iloc[:, cat_features_indices] = X.iloc[:, cat_features_indices].fillna("MISSING")
X_test_cb.iloc[:, cat_features_indices] = X_test_cb.iloc[:, cat_features_indices].fillna("MISSING")

cat_feature_names = X.columns[cat_features_indices]
for col in cat_feature_names:
    X[col] = X[col].astype(str).fillna("MISSING_STR")
    X_test_cb[col] = X_test_cb[col].astype(str).fillna("MISSING_STR")

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# --- Optuna для подбора гиперпараметров ---
def objective(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 500, 3000),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'depth': trial.suggest_int('depth', 4, 10),
        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1, 10),
        'border_count': trial.suggest_int('border_count', 32, 255),
        'loss_function': 'Logloss',
        'eval_metric': 'AUC',
        'cat_features': cat_features_indices,
        'auto_class_weights': 'Balanced',
        'early_stopping_rounds': 100,
        'verbose': 0,
        'task_type': "CPU"  # или "GPU"
    }

    oof_preds = np.zeros(len(X))
    
    for train_idx, val_idx in kf.split(X, y):
        X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

        model = CatBoostClassifier(**params)
        model.fit(X_tr, y_tr, eval_set=(X_val, y_val), use_best_model=True)
        oof_preds[val_idx] = model.predict_proba(X_val)[:, 1]

    score = roc_auc_score(y, oof_preds)
    return score

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)  # можно увеличить количество проб

print("Best params:", study.best_params)
print("Best AUC:", study.best_value)

# --- Обучение финальной модели с лучшими параметрами ---
best_params = study.best_params
best_params.update({
    'loss_function': 'Logloss',
    'eval_metric': 'AUC',
    'cat_features': cat_features_indices,
    'auto_class_weights': 'Balanced',
    'early_stopping_rounds': 100,
    'verbose': 100,
    'task_type': "CPU"
})

oof_preds = np.zeros(len(X))
test_preds = np.zeros(len(X_test_cb))

for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

    model = CatBoostClassifier(**best_params)
    model.fit(X_tr, y_tr, eval_set=(X_val, y_val), use_best_model=True)
    
    oof_preds[val_idx] = model.predict_proba(X_val)[:, 1]
    test_preds += model.predict_proba(X_test_cb)[:, 1] / 5

# --- Подбор оптимального порога ---
thresholds = np.linspace(0.01, 0.99, 100)
best_threshold = 0.5
best_score = 0.0

for t in thresholds:
    score = roc_auc_score(y, (oof_preds > t).astype(int))
    if score > best_score:
        best_score = score
        best_threshold = t

print(f"Best Binary AUC: {best_score}")
print(f"Best Threshold: {best_threshold}")

submission = pd.DataFrame({
    'customer': df_test['customer'],
    'target': (test_preds > best_threshold).astype(int)
})
submission.to_csv('answers.csv', index=False)

/tmp/ipykernel_52141/799712930.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0        MISSING
1           -2.0
2        MISSING
3        MISSING
4        MISSING
          ...
10032    MISSING
10033    MISSING
10034    MISSING
10035    MISSING
10036    MISSING
Name: a4fc43c630d53f6b4fc24dcea3cdfdd6, Length: 10037, dtype: object' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  X_test_cb.iloc[:, cat_features_indices] = X_test_cb.iloc[:, cat_features_indices].fillna("MISSING")
/tmp/ipykernel_52141/799712930.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0        MISSING
1        MISSING
2        MISSING
3        MISSING
4        MISSING
          ...
10032    MISSING
10033    MISSING
10034    MISSING
10035    MISSING
10036    MISSING
Name: 754dee610d3bc5ef654ef2b9c4328c2d, Length: 10037, dtype: object' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  X_test_cb.iloc[:, cat_features_indices] = X_test_cb.iloc[:, cat_features_indices].fillna("MISSING")
/tmp/ipykernel_52141/799712930.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0            0.0
1        MISSING
2        MISSING
3        MISSING
4            0.0
          ...
10032    MISSING
10033        0.0
10034        0.0
10035        0.0
10036        0.0
Name: 7218c484a45b5cf830285bff9b436a9e, Length: 10037, dtype: object' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  X_test_cb.iloc[:, cat_features_indices] = X_test_cb.iloc[:, cat_features_indices].fillna("MISSING")
[I 2025-11-28 15:47:21,478] A new study created in memory with name: no-name-98150361-367d-483c-af37-38d57fbb35f3
[I 2025-11-28 15:50:47,821] Trial 0 finished with value: 0.6733548688592909 and parameters: {'iterations': 1581, 'learning_rate': 0.18431962377722128, 'depth': 4, 'l2_leaf_reg': 9.240198968885624, 'border_count': 86}. Best is trial 0 with value: 0.6733548688592909.
[I 2025-11-28 15:58:51,410] Trial 1 finished with value: 0.6564162833617617 and parameters: {'iterations': 1791, 'learning_rate': 0.02934381092888146, 'depth': 10, 'l2_leaf_reg': 3.1732222283805624, 'border_count': 232}. Best is trial 0 with value: 0.6733548688592909.
[I 2025-11-28 16:06:00,295] Trial 2 finished with value: 0.6661927918218473 and parameters: {'iterations': 963, 'learning_rate': 0.04374973271595013, 'depth': 8, 'l2_leaf_reg': 8.620578767699085, 'border_count': 39}. Best is trial 0 with value: 0.6733548688592909.
[I 2025-11-28 16:11:37,759] Trial 3 finished with value: 0.6584312214909429 and parameters: {'iterations': 819, 'learning_rate': 0.057433958697481656, 'depth': 10, 'l2_leaf_reg': 1.0658331055551216, 'border_count': 180}. Best is trial 0 with value: 0.6733548688592909.
[I 2025-11-28 16:33:49,057] Trial 4 finished with value: 0.6721727709482815 and parameters: {'iterations': 1212, 'learning_rate': 0.017947667008712746, 'depth': 5, 'l2_leaf_reg': 7.444781661772782, 'border_count': 39}. Best is trial 0 with value: 0.6733548688592909.
[I 2025-11-28 16:42:19,118] Trial 5 finished with value: 0.6676052140128137 and parameters: {'iterations': 2963, 'learning_rate': 0.030474850782144902, 'depth': 7, 'l2_leaf_reg': 1.7281753396747086, 'border_count': 166}. Best is trial 0 with value: 0.6733548688592909.
[I 2025-11-28 16:48:37,803] Trial 6 finished with value: 0.6620725831842151 and parameters: {'iterations': 820, 'learning_rate': 0.104989319013352, 'depth': 10, 'l2_leaf_reg': 5.745904441845109, 'border_count': 52}. Best is trial 0 with value: 0.6733548688592909.
[I 2025-11-28 17:10:52,789] Trial 7 finished with value: 0.6706037057412133 and parameters: {'iterations': 2416, 'learning_rate': 0.014006781945253316, 'depth': 6, 'l2_leaf_reg': 2.7186207741811694, 'border_count': 172}. Best is trial 0 with value: 0.6733548688592909.
[I 2025-11-28 17:19:53,408] Trial 8 finished with value: 0.6712281116289778 and parameters: {'iterations': 2044, 'learning_rate': 0.05904214861154395, 'depth': 5, 'l2_leaf_reg': 2.1966575835701887, 'border_count': 46}. Best is trial 0 with value: 0.6733548688592909.
[I 2025-11-28 17:27:43,116] Trial 9 finished with value: 0.6663358344994532 and parameters: {'iterations': 2483, 'learning_rate': 0.05784726260382884, 'depth': 7, 'l2_leaf_reg': 2.8443226137636977, 'border_count': 245}. Best is trial 0 with value: 0.6733548688592909.
[I 2025-11-28 17:31:16,645] Trial 10 finished with value: 0.6701100112657439 and parameters: {'iterations': 1489, 'learning_rate': 0.2806419472346034, 'depth': 4, 'l2_leaf_reg': 9.882439845647836, 'border_count': 102}. Best is trial 0 with value: 0.6733548688592909.
[I 2025-11-28 17:34:46,068] Trial 11 finished with value: 0.6684904707044957 and parameters: {'iterations': 1321, 'learning_rate': 0.2815107416082747, 'depth': 4, 'l2_leaf_reg': 7.341609604245029, 'border_count': 91}. Best is trial 0 with value: 0.6733548688592909.
[I 2025-11-28 17:57:51,668] Trial 12 finished with value: 0.6697986507238899 and parameters: {'iterations': 1308, 'learning_rate': 0.010007749199231537, 'depth': 5, 'l2_leaf_reg': 7.265052814723104, 'border_count': 97}. Best is trial 0 with value: 0.6733548688592909.
[I 2025-11-28 18:04:25,602] Trial 13 finished with value: 0.6734186069659964 and parameters: {'iterations': 1884, 'learning_rate': 0.1333378928543633, 'depth': 5, 'l2_leaf_reg': 9.747071070903335, 'border_count': 74}. Best is trial 13 with value: 0.6734186069659964.
[I 2025-11-28 18:09:26,287] Trial 14 finished with value: 0.6733986862679416 and parameters: {'iterations': 1890, 'learning_rate': 0.14224498176339628, 'depth': 4, 'l2_leaf_reg': 9.950936792790483, 'border_count': 117}. Best is trial 13 with value: 0.6734186069659964.
[I 2025-11-28 18:16:31,676] Trial 15 finished with value: 0.6709118717195318 and parameters: {'iterations': 2017, 'learning_rate': 0.1049248079107148, 'depth': 6, 'l2_leaf_reg': 4.443940610918015, 'border_count': 138}. Best is trial 13 with value: 0.6734186069659964.
[W 2025-11-28 18:19:27,361] Trial 16 failed with parameters: {'iterations': 2292, 'learning_rate': 0.12364122745571741, 'depth': 6, 'l2_leaf_reg': 8.50238145455797, 'border_count': 128} because of the following error: KeyboardInterrupt('').
Traceback (most recent call last):
  File "/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/optuna/study/_optimize.py", line 205, in _run_trial
    value_or_values = func(trial)
  File "/tmp/ipykernel_52141/799712930.py", line 49, in objective
    model.fit(X_tr, y_tr, eval_set=(X_val, y_val), use_best_model=True)
  File "/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/catboost/core.py", line 5245, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, graph, sample_weight, None, None, None, None, baseline, use_best_model,
  File "/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/catboost/core.py", line 2410, in _fit
    self._train(
  File "/home/kirill/miniconda3/envs/DScource/lib/python3.10/site-packages/catboost/core.py", line 1790, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 5023, in _catboost._CatBoost._train
  File "_catboost.pyx", line 5072, in _catboost._CatBoost._train
KeyboardInterrupt
[W 2025-11-28 18:19:27,364] Trial 16 failed with value None.

KeyboardInterrupt:

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

# ... (Assume you have run the XGBoost training code from the previous step)
# ... (You have 'y' (true labels) and 'oof_preds' (probabilities) ready)

# --- 1. Find the Perfect Threshold for BINARY AUC ---
# We simulate the submission format on our validation data to find the best cutoff.

thresholds = np.linspace(0.01, 0.99, 100)
best_threshold = 0.5
best_binary_auc = 0.0

print("Searching for optimal threshold to maximize Binary AUC...")

for thresh in thresholds:
    # Binarize the OOF predictions
    binary_preds = (oof_preds >= thresh).astype(int)
    
    # Calculate AUC on the BINARY output (as the system will do)
    score = roc_auc_score(y, binary_preds)
    
    if score > best_binary_auc:
        best_binary_auc = score
        best_threshold = thresh

print(f"\nBest Threshold found: {best_threshold:.4f}")
print(f"Max validation Binary AUC: {best_binary_auc:.4f}")

# Check if we meet the requirement
if best_binary_auc > 0.7:
    print("✅ Success! The model is expected to pass the 0.7 barrier.")
else:
    print("⚠️ Warning: The model might struggle to reach 0.7. Try feature engineering or different models.")

# --- 2. Create the Submission File ---

# Apply the best threshold to the Test Probabilities
test_binary_predictions = (test_preds >= best_threshold).astype(int)

# Create DataFrame
submission = pd.DataFrame({
    'customer': df_test['customer'],
    'target': test_binary_predictions
})

# Verify constraints
print("\nSubmission Check:")
print(f"Unique values in target: {submission['target'].unique()}") # Should be [0 1] or [1 0]
print(f"Data Type: {submission['target'].dtype}") # Should be int32 or int64

# --- 3. Save ---
submission.to_csv('answers.csv', index=False)
print("File 'answers.csv' saved successfully.")

Gemini. XGBoost update

In [ ]:
import optuna
from optuna.integration import XGBoostPruningCallback
from optuna.samplers import TPESampler
from optuna.pruners import MedianPruner
import xgboost as xgb
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import warnings

# Suppress warnings for cleaner output
warnings.filterwarnings('ignore')

# ----------------------------
# 1. Config & Data Setup
# ----------------------------
target_col = 'target'       # Name of target variable
id_col = 'customer'         # ID column (will be dropped from features)

# Assumption: df_train and df_test are already loaded in memory
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

n_train = len(df_train)
train_with_target = df_train.copy()
test_df = df_test.copy()

# Concatenate for consistent encoding
full_data = pd.concat([train_with_target.drop(columns=[target_col], errors='ignore'),
                       test_df],
                      axis=0).reset_index(drop=True)

# ----------------------------
# 2. Basic Feature Engineering
# ----------------------------
# A. Row-wise null count
full_data['null_counts'] = full_data.isnull().sum(axis=1)

# B. Frequency encoding (for object/category)
object_cols = full_data.select_dtypes(include=['object', 'category']).columns.tolist()
for col in object_cols:
    full_data[f'{col}_freq'] = full_data[col].map(full_data[col].value_counts())

# C. Label encoding (safe conversion to int)
for col in object_cols:
    le = LabelEncoder()
    # Fill NaN with string to prevent LabelEncoder error
    full_data[col] = full_data[col].astype(str).fillna('##MISSING##')
    full_data[col] = le.fit_transform(full_data[col])

# Split back into X and X_test
X = full_data.iloc[:n_train, :].reset_index(drop=True)
X_test = full_data.iloc[n_train:, :].reset_index(drop=True)

# Extract Target
y = df_train[target_col].reset_index(drop=True)

# Drop ID columns
if id_col in X.columns:
    X = X.drop(columns=[id_col])
if id_col in X_test.columns:
    X_test = X_test.drop(columns=[id_col])

# ----------------------------
# 3. Class Imbalance (scale_pos_weight)
# ----------------------------
pos = float((y == 1).sum())
neg = float((y == 0).sum())
scale_pos_weight = neg / pos if pos > 0 else 1.0
print(f"Calculated scale_pos_weight: {scale_pos_weight:.2f}")

# ----------------------------
# 4. Optuna Objective with Target Encoding inside CV
# ----------------------------
def objective(trial):
    # UPDATED: Using suggest_float with log=True replaces suggest_loguniform
    params = {
        'objective': 'binary:logistic',
        'eval_metric': 'auc',
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        'lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 20),
        'verbosity': 0,
        'seed': 42,
        'scale_pos_weight': scale_pos_weight,
    }

    kf_inner = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = []

    for tr_idx, val_idx in kf_inner.split(X, y):
        X_tr = X.iloc[tr_idx].copy().reset_index(drop=True)
        X_val = X.iloc[val_idx].copy().reset_index(drop=True)
        y_tr = y.iloc[tr_idx].reset_index(drop=True)
        y_val = y.iloc[val_idx].reset_index(drop=True)

        # === Target Encoding Inside Fold ===
        # Select high cardinality features
        cat_features = [c for c in X_tr.columns
                        if ('freq' not in c and 'null' not in c and c != id_col and X_tr[c].nunique() > 10)]

        smoothing = 10
        for col in cat_features:
            # Calculate stats on TRAIN ONLY
            temp = pd.DataFrame({col: X_tr[col], target_col: y_tr})
            agg = temp.groupby(col)[target_col].agg(['count', 'mean'])
            counts = agg['count']
            means = agg['mean']
            global_mean = y_tr.mean()

            # Smooth
            smooth = (counts * means + smoothing * global_mean) / (counts + smoothing)
            smooth_map = smooth.to_dict()

            # Map to train and val
            X_tr[f'{col}_target_enc'] = X_tr[col].map(smooth_map)
            X_val[f'{col}_target_enc'] = X_val[col].map(smooth_map)

            # Fill unseen values with global mean
            X_tr[f'{col}_target_enc'].fillna(global_mean, inplace=True)
            X_val[f'{col}_target_enc'].fillna(global_mean, inplace=True)

        # === Training ===
        dtrain = xgb.DMatrix(X_tr, label=y_tr)
        dval = xgb.DMatrix(X_val, label=y_val)

        pruning_cb = XGBoostPruningCallback(trial, "valid-auc")

        bst = xgb.train(
            params,
            dtrain,
            num_boost_round=2000,
            evals=[(dval, 'valid')],
            early_stopping_rounds=100,
            verbose_eval=False,
            callbacks=[pruning_cb]
        )

        # UPDATED: Use iteration_range instead of ntree_limit
        best_iteration = bst.best_iteration
        val_pred = bst.predict(dval, iteration_range=(0, best_iteration + 1))

        scores.append(roc_auc_score(y_val, val_pred))

    return np.mean(scores)

# ----------------------------
# 5. Run Optimization
# ----------------------------
sampler = TPESampler(seed=42)
pruner = MedianPruner(n_startup_trials=5, n_warmup_steps=10)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=pruner)

N_TRIALS = 50
print(f"Starting Optuna optimization for {N_TRIALS} trials...")
study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=True)

print("\nBest Trial:")
print(f"  CV AUC = {study.best_value:.5f}")
print("  Params:")
for k, v in study.best_params.items():
    print(f"    {k}: {v}")

# ----------------------------
# 6. Final Training & OOF Generation
# ----------------------------
best = study.best_params
final_params = {
    'objective': 'binary:logistic',
    'eval_metric': 'auc',
    'learning_rate': best['learning_rate'],
    'max_depth': int(best['max_depth']),
    'subsample': best['subsample'],
    'colsample_bytree': best['colsample_bytree'],
    'alpha': best['reg_alpha'],
    'lambda': best['reg_lambda'],
    'min_child_weight': int(best['min_child_weight']),
    'verbosity': 0,
    'seed': 42,
    'scale_pos_weight': scale_pos_weight,
}

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
oof_preds = np.zeros(len(X))
test_preds = np.zeros(len(X_test))

print("\nTraining final models with best params...")

for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
    X_tr = X.iloc[train_idx].copy().reset_index(drop=True)
    X_val = X.iloc[val_idx].copy().reset_index(drop=True)
    y_tr = y.iloc[train_idx].reset_index(drop=True)
    y_val = y.iloc[val_idx].reset_index(drop=True)

    # === Target Encoding (Exact same logic as CV) ===
    cat_features = [c for c in X_tr.columns
                    if ('freq' not in c and 'null' not in c and c != id_col and X_tr[c].nunique() > 10)]
    
    # Copy X_test for this fold to apply mapping safely
    X_test_fold = X_test.copy().reset_index(drop=True)
    smoothing = 10

    for col in cat_features:
        temp = pd.DataFrame({col: X_tr[col], target_col: y_tr})
        agg = temp.groupby(col)[target_col].agg(['count', 'mean'])
        counts = agg['count']
        means = agg['mean']
        global_mean = y_tr.mean()

        smooth = (counts * means + smoothing * global_mean) / (counts + smoothing)
        smooth_map = smooth.to_dict()

        X_tr[f'{col}_target_enc'] = X_tr[col].map(smooth_map)
        X_val[f'{col}_target_enc'] = X_val[col].map(smooth_map)
        # Apply Train map to Test
        X_test_fold[f'{col}_target_enc'] = X_test_fold[col].map(smooth_map)

        # Fill NaNs
        X_tr[f'{col}_target_enc'].fillna(global_mean, inplace=True)
        X_val[f'{col}_target_enc'].fillna(global_mean, inplace=True)
        X_test_fold[f'{col}_target_enc'].fillna(global_mean, inplace=True)

    # === Train ===
    dtrain = xgb.DMatrix(X_tr, label=y_tr)
    dval = xgb.DMatrix(X_val, label=y_val)
    dtest = xgb.DMatrix(X_test_fold)

    bst = xgb.train(
        final_params,
        dtrain,
        num_boost_round=2000,
        evals=[(dval, 'valid')],
        early_stopping_rounds=100,
        verbose_eval=False
    )

    # UPDATED: iteration_range
    best_iteration = bst.best_iteration
    val_pred = bst.predict(dval, iteration_range=(0, best_iteration + 1))
    test_pred = bst.predict(dtest, iteration_range=(0, best_iteration + 1))

    oof_preds[val_idx] = val_pred
    test_preds += test_pred / kf.get_n_splits()

    fold_score = roc_auc_score(y_val, val_pred)
    print(f"Fold {fold+1} AUC: {fold_score:.4f}")

overall_auc = roc_auc_score(y, oof_preds)
print(f"--- Overall CV AUC (final): {overall_auc:.4f} ---")

# ----------------------------
# 7. Submission
# ----------------------------
submission = pd.DataFrame({
    id_col: df_test[id_col],
    'target': test_preds
})
print("Head of submission:")
print(submission.head())

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

# ... (Assume you have run the XGBoost training code from the previous step)
# ... (You have 'y' (true labels) and 'oof_preds' (probabilities) ready)

# --- 1. Find the Perfect Threshold for BINARY AUC ---
# We simulate the submission format on our validation data to find the best cutoff.

thresholds = np.linspace(0.01, 0.99, 100)
best_threshold = 0.5
best_binary_auc = 0.0

print("Searching for optimal threshold to maximize Binary AUC...")

for thresh in thresholds:
    # Binarize the OOF predictions
    binary_preds = (oof_preds >= thresh).astype(int)
    
    # Calculate AUC on the BINARY output (as the system will do)
    score = roc_auc_score(y, binary_preds)
    
    if score > best_binary_auc:
        best_binary_auc = score
        best_threshold = thresh

print(f"\nBest Threshold found: {best_threshold:.4f}")
print(f"Max validation Binary AUC: {best_binary_auc:.4f}")

# Check if we meet the requirement
if best_binary_auc > 0.7:
    print("✅ Success! The model is expected to pass the 0.7 barrier.")
else:
    print("⚠️ Warning: The model might struggle to reach 0.7. Try feature engineering or different models.")

# --- 2. Create the Submission File ---

# Apply the best threshold to the Test Probabilities
test_binary_predictions = (test_preds >= best_threshold).astype(int)

# Create DataFrame
submission = pd.DataFrame({
    'customer': df_test['customer'],
    'target': test_binary_predictions
})

# Verify constraints
print("\nSubmission Check:")
print(f"Unique values in target: {submission['target'].unique()}") # Should be [0 1] or [1 0]
print(f"Data Type: {submission['target'].dtype}") # Should be int32 or int64

# --- 3. Save ---
submission.to_csv('answers.csv', index=False)
print("File 'answers.csv' saved successfully.")